name: Release
on:
  push:
    tags: ["v*.*.*"]
jobs:
  lint-python:
    name: Run Python lint
    uses: kuba2k2/kuba2k2/.github/workflows/lint-python.yml@master
  publish-pypi:
    name: Publish PyPI package
    needs:
      - lint-python
    uses: kuba2k2/kuba2k2/.github/workflows/publish-pypi.yml@master
    secrets:
      PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Add GitHub release assets
        uses: softprops/action-gh-release@v1
        with:
          files: |
            README.md
